### ISSUE TITLE
Several major issues

### ISSUE THREAD

**Issue by Sterophonick** [jeffman/Mother2GbaTranslation#10]
- Calling your dad crashes the game, but calling your mom works fine, but she acts like your dad. This is 
   not the case in the cave of the past. wat
 - Game crashes on 3rd prayer of Giygas Fight
 - Displaying numbers is weird, mainly when they are variables, such as how much experience you need 
   to get to the next level. This only happens in dialogue sequences.
 - Displaying choices such as Yes or No displays a graphical glitch.
 - Items menu has trouble rendering items, sometimes items will not appear unless highlighted, other 
   times, the screen will not be cleared, and the text will overlap. Most of the time, it will display a 
   graphical glitch.

New strings are on my fork.

**Comment by Sterophonick** [comment]
Also, near a specific door in Fire Spring, for some reason the game jumps execution to an invalid address, causing a crash. rip

**Comment by PhoenixBound** [comment]
The "mom call acting like dad" might be caused by a typo in [m12-misctext.json](https://github.com/jeffman/Mother2GbaTranslation/blob/master/working/m12-misctext.json#L328-L340) where Dad and Mom's names are switched.

**Comment by Sterophonick** [comment]
Also fixed the game crashing. wat.

**Comment by jeffman** [comment]
@Sterophonick Is this resolved?

**Comment by Sterophonick** [comment]
yes
