### ISSUE TITLE
Fix issue with Stonehenge Base map

### ISSUE THREAD

**Issue by Sterophonick** [jeffman/Mother2GbaTranslation#131]
![Mother_12_Japan_1598628328602](https://user-images.githubusercontent.com/34801996/91604268-345f2800-e923-11ea-9223-43483d3e50ce.png)
![Mother_12_Japan_1598628266673](https://user-images.githubusercontent.com/34801996/91604271-3628eb80-e923-11ea-9c23-d79f0bcb74a2.png)

**Comment by Lorenzooone** [comment]
Issue is sttill there.
Was looking at the wrong part of the map.
It's better, but not fixed.
