### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by badass-boss** [jeffman/Mother2GbaTranslation#137]
Is this translation officially finished or not?? There is no changelog file here so please clarify what state it is in, whether it is officially completed or just translated but needs bugfixes or anything else. Maybe I can contribute to fixes as long as I can get hold of the tools

**Comment by Lorenzooone** [comment]
Hello,
The translation is mostly done, however, as you can see from the https://github.com/jeffman/Mother2GbaTranslation/issues tab, there are some things that need to be fixed before it can be considered ready for release. The plan is to have 0 Issues remaining. They are also divided by category in this tab: https://github.com/jeffman/Mother2GbaTranslation/projects
If you wish to contribute, the tools are all included in the project, and the README explains how to compile it.
Hope this helps. :)
