### ISSUE TITLE
Item selection bugs

### ISSUE THREAD

**Issue by PhoenixBound** [jeffman/Mother2GbaTranslation#26]
Most of the item menu display has been implemented by now, but a few things remain:

* The flashing cursor isn't cleared when it is moved
* The menu does not print items properly when there is a single party member or the item menu is brought up in a battle. (Possibly related to this, redrawing the menu after Help text doesn't happen.)
* When an item is chosen, the game doesn't currently take into account whether it's equipped or not and always prints it at the same X coordinate.

**Comment by leo60228** [comment]
All of these issues seem to be fixed.
![image](https://user-images.githubusercontent.com/8355305/85186224-d7c9f780-b265-11ea-8d59-0900a10c7fa7.png)

**Comment by PhoenixBound** [comment]
Thank you for checking this.
