### ISSUE TITLE
Phone window clearing doesn't work properly

### ISSUE THREAD

**Issue by PhoenixBound** [jeffman/Mother2GbaTranslation#39]
In most places with phones, once a person to call is chosen, the text for phone contacts remains in the tiles. When the text for the phone call is displayed, the phone contacts' names obscure parts of the text in places where there was previously no text.

It's a little hard to explain in words, but we've encountered it for a while. Example screenshot (Lost Underworld gets hit especially hard since it has such a short text line):

![image](https://cdn.discordapp.com/attachments/448360568428953611/541038435704766475/howmany.png)

**Comment by PhoenixBound** [comment]
This was worked around in d78af6a.

**Comment by Lorenzooone** [comment]
Same happens with shops. And Stored Goods iirc.
