### ISSUE TITLE
XKAS -> ARMIPS

### ISSUE THREAD

**Issue by Normmatt** [jeffman/Mother2GbaTranslation#7]
I know you've got a lot of stuff already working with xkas but as your aware that's pretty much dead and unavailable these days.

Would you consider moving to something like [ARMIPS](https://github.com/Kingcom/armips) which is open source and supports all the features of xkas and also has built in support for table files and a lot of other useful features.

**Comment by jeffman** [comment]
I'll definitely take a look -- as helpful as xkas was for me, it has some weird quirks. Thanks for letting me know about ARMIPS!

**Comment by jeffman** [comment]
Looks like it's better than xkas for what I need, so I've gone ahead and migrated everything over. It all seems to work on my end so far so I'll close this.
